FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY gradlew .
COPY gradlew.bat .
COPY gradle ./gradle
COPY build.gradle .
COPY settings.gradle .
COPY gradle.properties .
COPY src ./src

RUN chmod +x gradlew

CMD ["./gradlew", "clean", "test", "--no-daemon"]